### PR TITLE
feat: Add Missing Methods for Blueprints

### LINKED ISSUE #21: Add Missing Methods for Blueprints
Some endpoints of the following section can't be hit from this SDK. 

We would like to ensure that all endpoints can be hit. For this issue, we would like to build out the Blueprints

Some of these methods may already exist.  If so no need to change/update them, just point out that they already exist and we will close the issue.  This is just to bring every SDK we have on par with all the methods available.

Check all the endpoints [here](https://api.novu.co/api#/default/BlueprintController_getGroupedBlueprints) and add the missing ones.

### PR DESCRIPTION
**Pull request by sccalabr**
Resolves https://github.com/novuhq/novu-elixir/issues/21

### CODE REVIEW

**Review by doomspork — APPROVED** [review]

**Comment by sccalabr** [comment]
@doomspork should I have gotten a form to fill out for hacktoberfest by now?

**Comment by btkostner** [comment]
@sccalabr Please refer to the hacktoberfest docs about participation. As far as I know, you will not get a form to fill out as you should have registered first.

> Register anytime between September 26 and October 31

https://hacktoberfest.com/participation/

**Comment by sccalabr** [comment]
@btkostner novu was doing something as well but I haven't heard yet

https://novu.co/hacktoberfest/

**Comment by unicodeveloper** [comment]
@sccalabr I sent a form on Discord for folks to fill. Are you on Novu discord?

**Comment by sccalabr** [comment]
@unicodeveloper i am not

**Comment by unicodeveloper** [comment]
@sccalabr Please fill this form https://airtable.com/app1F6yJ4LMaqorgy/shr1VfoGxfUqytgsx

**Comment by sccalabr** [comment]
Hi @unicodeveloper just wondering if this has been shipped. I submitted the form last month but havent heard anything since

**Comment by unicodeveloper** [comment]
You will be alerted when it has been shipped @sccalabr

**Comment by sccalabr** [comment]
@unicodeveloper do you have a rough timeline when you expect it be shipped? I havent received an email yet so I am wondering if I missed something

**Pull request merged**
